# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleborrow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_query17(object):
    def setupUi(self, query):
        query.setObjectName("query")
        query.resize(621, 325)
        self.pushButton = QtWidgets.QPushButton(query)
        self.pushButton.setGeometry(QtCore.QRect(260, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(query)
        self.label.setGeometry(QtCore.QRect(140, 100, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(query)
        self.lineEdit.setGeometry(QtCore.QRect(230, 100, 201, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(query)
        QtCore.QMetaObject.connectSlotsByName(query)
        self.pushButton.clicked.connect(query.deleborrow)

    def retranslateUi(self, query):
        _translate = QtCore.QCoreApplication.translate
        query.setWindowTitle(_translate("query", "删除借阅信息表"))
        self.pushButton.setText(_translate("query", "删除"))
        self.label.setText(_translate("query", "借阅证号:"))
