# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ok.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog2):
        Dialog2.setObjectName("Dialog2")
        Dialog2.resize(486, 580)
        self.label = QtWidgets.QLabel(Dialog2)
        self.label.setGeometry(QtCore.QRect(190, 40, 131, 61))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog2)
        self.pushButton.setGeometry(QtCore.QRect(110, 130, 251, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog2)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 230, 251, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog2)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 330, 251, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog2)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 420, 251, 61))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog2)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)
        self.pushButton.clicked.connect(Dialog2.query)

        self.retranslateUi(Dialog2)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)
        self.pushButton_2.clicked.connect(Dialog2.add)

        self.retranslateUi(Dialog2)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)
        self.pushButton_3.clicked.connect(Dialog2.update)

        self.retranslateUi(Dialog2)
        QtCore.QMetaObject.connectSlotsByName(Dialog2)
        self.pushButton_4.clicked.connect(Dialog2.dele)



    def retranslateUi(self, Dialog2):
        _translate = QtCore.QCoreApplication.translate
        Dialog2.setWindowTitle(_translate("Dialog2", "图书管理系统"))
        self.label.setText(_translate("Dialog2", "图书管理系统"))
        self.pushButton.setText(_translate("Dialog2", "查询"))
        self.pushButton_2.setText(_translate("Dialog2", "添加"))
        self.pushButton_3.setText(_translate("Dialog2", "修改"))
        self.pushButton_4.setText(_translate("Dialog2", "删除"))
